import { IMessage } from "@/types";

export const Messages: IMessage[] = [
  { id: 1, text: "Hello, how can I help you today?", type: "bot" },
  { id: 2, text: "**I need help** with markdown syntax.", type: "user" },
  {
    id: 3,
    text: "Sure! Here’s how you write a heading:\n\n# Heading 1",
    type: "bot",
  },
  { id: 4, text: "Can I see a list example?", type: "user" },
  { id: 5, text: "Yes!\n\n- Item 1\n- Item 2\n- Item 3", type: "bot" },
  { id: 6, text: "What about inline code?", type: "user" },
  {
    id: 7,
    text: "You can use backticks like this: `let x = 10;`",
    type: "bot",
  },
  { id: 8, text: "Nice. How do I bold text?", type: "user" },
  { id: 9, text: "Use double asterisks: `**bold text**`", type: "bot" },
  { id: 10, text: "Thanks!", type: "user" },
  { id: 11, text: "You're welcome! 😊", type: "bot" },
  { id: 12, text: "Can you show me a JS function?", type: "user" },
  {
    id: 13,
    text: "```js\nfunction greet() {\n  return 'Hello';\n}\n```",
    type: "bot",
  },
  { id: 14, text: "How about a Python loop?", type: "user" },
  {
    id: 15,
    text: "```python\nfor i in range(5):\n    print(i)\n```",
    type: "bot",
  },
  { id: 16, text: "Can markdown support images?", type: "user" },
  { id: 17, text: "Yes! `![alt text](image-url)`", type: "bot" },
  { id: 18, text: "# Heading Example", type: "user" },
  { id: 19, text: "That's a valid H1 heading!", type: "bot" },
  { id: 20, text: "Create a checklist", type: "user" },
  { id: 21, text: "- [x] Task 1\n- [ ] Task 2", type: "bot" },
  { id: 22, text: "Nice, what’s a blockquote?", type: "user" },
  { id: 23, text: "> This is a blockquote", type: "bot" },
  { id: 24, text: "Make a table for me.", type: "user" },
  {
    id: 25,
    text: "| Name | Age |\n|------|-----|\n| John | 25  |",
    type: "bot",
  },
  { id: 26, text: "How to add links?", type: "user" },
  { id: 27, text: "[Click here](https://example.com)", type: "bot" },
  { id: 28, text: "Do you support emoji?", type: "user" },
  { id: 29, text: "Yes 😄", type: "bot" },
  { id: 30, text: "Can I mix markdown?", type: "user" },
  { id: 31, text: "**Bold** and `code` and - lists", type: "bot" },
  { id: 32, text: "How to italicize text?", type: "user" },
  { id: 33, text: "Use `*italic*` or `_italic_`", type: "bot" },
  { id: 34, text: "Cool, what’s strikethrough?", type: "user" },
  { id: 35, text: "Use `~~strikethrough~~`", type: "bot" },
  { id: 36, text: "Show multi-language snippet", type: "user" },
  {
    id: 37,
    text: "```js\nlet x = 10;\n```\n```python\nx = 10\n```",
    type: "bot",
  },
  { id: 38, text: "How about nested lists?", type: "user" },
  { id: 39, text: "- Item 1\n  - Subitem 1\n  - Subitem 2", type: "bot" },
  { id: 40, text: "Display horizontal line", type: "user" },
  { id: 41, text: "---", type: "bot" },
  { id: 42, text: "Can I highlight text?", type: "user" },
  {
    id: 43,
    text: "Markdown doesn't support highlights natively, but you can use HTML: `<mark>highlight</mark>`",
    type: "bot",
  },
  { id: 44, text: "How to escape characters?", type: "user" },
  { id: 45, text: "Use backslash: `\\*not italic\\*`", type: "bot" },
  { id: 46, text: "Is there math support?", type: "user" },
  {
    id: 47,
    text: "Only in markdown variants like KaTeX/MathJax:\n\n`$E=mc^2$`",
    type: "bot",
  },
  { id: 48, text: "Thanks for all the help!", type: "user" },
  { id: 49, text: "Anytime! 🚀", type: "bot" },
  { id: 50, text: "Bye!", type: "user" },
];
